name: 🚀 Release

on:
  push:
    branches:
      - main # Triggers when code is pushed or merged to main

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
      - name: ⬇️ Checkout Repo
        uses: actions/checkout@v7
        with:
          fetch-depth: 0 # Needed for changelog/tag

      - name: 🧰 Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 18

      - name: 📦 Install Dependencies
        run: npm install

      - name: 🚀 Run Release (standard-version)
        env:
          RELEASE_BOT_EMAIL: ${{ secrets.RELEASE_BOT_EMAIL }}
        run: |
          git config --global user.email "${RELEASE_BOT_EMAIL:-rakibulmehedi.dev@gmail.com}"
          git config --global user.name "Rakibul Islam Mehedi (Release Bot)"
          npm run release
          git push --follow-tags origin main
